const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    GETWEEKWISE: "GETWEEKWISE",
    SET_REVIEW: "SET_REVIEW",
    GETEACHDAY: "GETEACHDAY",
    GETFATSECRET:"GETFATSECRET"
}

export default Constants;